FROM python:3.10

WORKDIR /app

COPY install_poetry.py .
COPY pyproject.toml .

RUN [ "python3", "install_poetry.py" ]
ENV PATH="${PATH}:/root/.poetry/bin:/root/.local/bin"
RUN /bin/bash -c 'poetry update && poetry install'

WORKDIR /app/src
CMD [ "poetry", "run", "celery", "-A", "tasks", "worker", "--loglevel=INFO" ]
