version: '3.8'
services:
  redis:
    image: redis:7.0.11-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data

  celeryworker:
    build:
      context: .
      dockerfile: ./Dockerfile.celery
    command:
      - entrypoint.sh
      - celery --app=tasks:app worker --loglevel=INFO -n docker@%h
    restart: always
    init: true
    environment:
      - CELERY_BROKER=redis://redis:6379/0
    volumes:
      - ./src:/app/src
    depends_on:
      - redis

volumes:
  redis:
